-- Altering the Timestamp Format so that the feature RESOLUTION_RESOLUTIONDATE can be read as a timestamp
ALTER SESSION SET TIMESTAMP_INPUT_FORMAT = 'YYYY-MM-DD"T"HH24:MI:SS.FFTZHTZM';
--This table groups by original project name
    --I have created a table that selects the original tickets that has been created.
WITH ORIGIN_TICKETS AS (
    SELECT *
    FROM SANDBOX_DB.SANDBOX_HECTOR_STANYER.JIRA_TICKETS_SANDBOX
WHERE SUMMARY NOT REGEXP 'IT-.*'
)
SELECT  ORIGIN_TICKETS.PROJECT_NAME AS Origin_PROJECT_NAME,
       COUNT(IFF(ORIGINAL_ISSUE_KEY IS NOT NULL ,ORIGIN_TICKETS.ISSUE_KEY,NULL))*100/COUNT(*) AS RATIO_MOVED_TICKETS,
       COUNT(IFF(ORIGIN_TICKETS.ISSUETYPE_NAME = 'IT Help', ORIGIN_TICKETS.ISSUE_KEY, NULL))/COUNT(*)*100 AS RATIO_INL_TICKETS,
       AVG(DATEDIFF(hour, ORIGIN_TICKETS.CREATED, TRANS_TICKETS.CREATED)) AS AVG_TIME_TO_TRANS_HOURS,
       AVG(IFF(TRANS_TICKETS.ISSUE_KEY IS NOT NULL, DATEDIFF(hour, ORIGIN_TICKETS.CREATED, TO_TIMESTAMP(TRANS_TICKETS.RESOLUTION_RESOLUTIONDATE)),DATEDIFF(hour, ORIGIN_TICKETS.CREATED, TO_TIMESTAMP(ORIGIN_TICKETS.RESOLUTION_RESOLUTIONDATE)))) AS OVERALL_AVG_HOURS,
       AVG(IFF(TRANS_TICKETS.ISSUE_KEY IS NOT NULL, DATEDIFF(hour, ORIGIN_TICKETS.CREATED, TO_TIMESTAMP(TRANS_TICKETS.RESOLUTION_RESOLUTIONDATE)),NULL)) AS AVG_TIME_TO_RES_FOR_TRANS_TICKET_HOURS,
       AVG(IFF(TRANS_TICKETS.ISSUE_KEY IS NOT NULL, NULL ,DATEDIFF(hour, ORIGIN_TICKETS.CREATED, TO_TIMESTAMP(ORIGIN_TICKETS.RESOLUTION_RESOLUTIONDATE)))) AS AVG_TIME_TO_RES_FOR_NON_TRANS_TICKETS_HOURS
FROM ORIGIN_TICKETS
LEFT JOIN ( SELECT *, SUBSTRING(SUMMARY,1, 8) AS ORIGINAL_ISSUE_KEY
    FROM SANDBOX_DB.SANDBOX_HECTOR_STANYER.JIRA_TICKETS_SANDBOX
    WHERE SUMMARY REGEXP 'IT-.*') AS TRANS_TICKETS
ON ORIGIN_TICKETS.ISSUE_KEY = TRANS_TICKETS.ORIGINAL_ISSUE_KEY
WHERE ORIGIN_TICKETS.CREATED > TO_TIMESTAMP('2021-03-01', 'YYYY-MM-DD')
   GROUP BY Origin_PROJECT_NAME;

--This table groups by the transistion project name
    --I have created a table that selects the transistioned tickets that has been created.
WITH ORIGIN_TICKETS AS (
    SELECT *
    FROM SANDBOX_DB.SANDBOX_HECTOR_STANYER.JIRA_TICKETS_SANDBOX
WHERE SUMMARY NOT REGEXP 'IT-.*'
)
SELECT TRANS_TICKETS.PROJECT_NAME AS TRANS_PROJECT_NAME,
       COUNT(IFF(ORIGIN_TICKETS.ISSUETYPE_NAME = 'IT Help', ORIGIN_TICKETS.ISSUE_KEY, NULL))/COUNT(*)*100 AS RATIO_INL_TICKETS,
       AVG(DATEDIFF(hour, ORIGIN_TICKETS.CREATED, TRANS_TICKETS.CREATED)) AS AVG_TIME_TO_TRANS_HOURS,
       AVG(IFF(ORIGIN_TICKETS.ISSUE_KEY IS NOT NULL, DATEDIFF(hour, ORIGIN_TICKETS.CREATED, TO_TIMESTAMP(TRANS_TICKETS.RESOLUTION_RESOLUTIONDATE)),DATEDIFF(hour, ORIGIN_TICKETS.CREATED, TO_TIMESTAMP(ORIGIN_TICKETS.RESOLUTION_RESOLUTIONDATE)))) AS OVERALL_AVG_HOURS,
       AVG(IFF(TRANS_TICKETS.ISSUE_KEY IS NOT NULL, DATEDIFF(hour, ORIGIN_TICKETS.CREATED, TO_TIMESTAMP(TRANS_TICKETS.RESOLUTION_RESOLUTIONDATE)),NULL)) AS AVG_TIME_TO_RES_FOR_TRANS_TICKET_HOURS,
       AVG(IFF(TRANS_TICKETS.ISSUE_KEY IS NOT NULL, NULL ,DATEDIFF(hour, ORIGIN_TICKETS.CREATED, TO_TIMESTAMP(ORIGIN_TICKETS.RESOLUTION_RESOLUTIONDATE)))) AS AVG_TIME_TO_RES_FOR_NON_TRANS_TICKETS_HOURS
FROM ORIGIN_TICKETS
LEFT JOIN ( SELECT *, SUBSTRING(SUMMARY,1, 8) AS ORIGINAL_ISSUE_KEY
    FROM SANDBOX_DB.SANDBOX_HECTOR_STANYER.JIRA_TICKETS_SANDBOX
    WHERE SUMMARY REGEXP 'IT-.*') AS TRANS_TICKETS
ON ORIGIN_TICKETS.ISSUE_KEY = TRANS_TICKETS.ORIGINAL_ISSUE_KEY
WHERE ORIGIN_TICKETS.CREATED > TO_TIMESTAMP('2021-03-01', 'YYYY-MM-DD')
       GROUP BY TRANS_PROJECT_NAME;

--no grouping
WITH ORIGIN_TICKETS AS (
    SELECT *
    FROM SANDBOX_DB.SANDBOX_HECTOR_STANYER.JIRA_TICKETS_SANDBOX
WHERE SUMMARY NOT REGEXP 'IT-.*'
)
SELECT  COUNT(IFF(ORIGINAL_ISSUE_KEY IS NOT NULL ,ORIGIN_TICKETS.ISSUE_KEY,NULL))*100/COUNT(*) AS RATIO_MOVED_TICKETS,
       COUNT(IFF(ORIGIN_TICKETS.ISSUETYPE_NAME = 'IT Help', ORIGIN_TICKETS.ISSUE_KEY, NULL))/COUNT(*)*100 AS RATIO_INL_TICKETS,
       AVG(DATEDIFF(hour, ORIGIN_TICKETS.CREATED, TRANS_TICKETS.CREATED)) AS AVG_TIME_TO_TRANS_HOURS,
       SUM(DATEDIFF(hour, ORIGIN_TICKETS.CREATED, TRANS_TICKETS.CREATED)) AS SUM_TIME_TRANS_HOURS,
       AVG(IFF(TRANS_TICKETS.ISSUE_KEY IS NOT NULL, DATEDIFF(hour, ORIGIN_TICKETS.CREATED, TO_TIMESTAMP(TRANS_TICKETS.RESOLUTION_RESOLUTIONDATE)),DATEDIFF(hour, ORIGIN_TICKETS.CREATED, TO_TIMESTAMP(ORIGIN_TICKETS.RESOLUTION_RESOLUTIONDATE)))) AS OVERALL_AVG_HOURS,
       AVG(IFF(TRANS_TICKETS.ISSUE_KEY IS NOT NULL, DATEDIFF(hour, ORIGIN_TICKETS.CREATED, TO_TIMESTAMP(TRANS_TICKETS.RESOLUTION_RESOLUTIONDATE)),NULL)) AS AVG_TIME_TO_RES_FOR_TRANS_TICKET_HOURS,
       AVG(IFF(TRANS_TICKETS.ISSUE_KEY IS NOT NULL, NULL, DATEDIFF(hour, ORIGIN_TICKETS.CREATED, TO_TIMESTAMP(ORIGIN_TICKETS.RESOLUTION_RESOLUTIONDATE)))) AS AVG_TIME_TO_RES_FOR_NON_TRANS_TICKETS_HOURS,
       AVG_TIME_TO_RES_FOR_TRANS_TICKET_HOURS - AVG_TIME_TO_RES_FOR_NON_TRANS_TICKETS_HOURS AS DIFF_AVG_RES_TIME_OF_TRANS_NON_TRANS_TICKETS_HOURS
FROM ORIGIN_TICKETS
LEFT JOIN ( SELECT *, SUBSTRING(SUMMARY,1, 8) AS ORIGINAL_ISSUE_KEY
    FROM SANDBOX_DB.SANDBOX_HECTOR_STANYER.JIRA_TICKETS_SANDBOX
    WHERE SUMMARY REGEXP 'IT-.*') AS TRANS_TICKETS
ON ORIGIN_TICKETS.ISSUE_KEY = TRANS_TICKETS.ORIGINAL_ISSUE_KEY
WHERE ORIGIN_TICKETS.CREATED > TO_TIMESTAMP('2021-03-01', 'YYYY-MM-DD');

WITH ORIGIN_TICKETS AS (
    SELECT *
    FROM SANDBOX_DB.SANDBOX_HECTOR_STANYER.JIRA_TICKETS_SANDBOX
WHERE SUMMARY NOT REGEXP 'IT-.*'
)
SELECT SUM(DATEDIFF(hour, ORIGIN_TICKETS.CREATED, TRANS_TICKETS.CREATED)) AS SUM_TIME_TRANS_HOURS,
       TRANS_TICKETS.PROJECT_NAME
FROM ORIGIN_TICKETS
LEFT JOIN ( SELECT *, SUBSTRING(SUMMARY,1, 8) AS ORIGINAL_ISSUE_KEY
    FROM SANDBOX_DB.SANDBOX_HECTOR_STANYER.JIRA_TICKETS_SANDBOX
    WHERE SUMMARY REGEXP 'IT-.*') AS TRANS_TICKETS
ON ORIGIN_TICKETS.ISSUE_KEY = TRANS_TICKETS.ORIGINAL_ISSUE_KEY
WHERE ORIGIN_TICKETS.CREATED > TO_TIMESTAMP('2021-03-01', 'YYYY-MM-DD')
GROUP BY TRANS_TICKETS.PROJECT_NAME;
